name: CI com Java e Quarkus
on: push
env:
  MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
  MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
jobs:
  testes:
    environment: testing
    runs-on: ubuntu-latest
    # https://hub.docker.com/_/node
    container:
      image: openjdk:11
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: estudo.0iiaa3o.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Instalar dependencias
        run: mvn -B package --file pom.xml
      - name: Rodando testes
        run: mvn test

